language: c

script: make && make check

matrix:
  include:
   - os: linux
     dist: trusty
     sudo: required
   - os: osx
     osx_image: xcode7.3

compiler:
 - clang
 - gcc

addons:
  apt:
    packages:
    - libyajl-dev
    - libyaml-dev

before_install:
 - if [[ "$TRAVISOS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVISOS_NAME" == "osx" ]]; then brew install yajl libyaml; fi
