language: c

script: make && make check

matrix:
  include:
   - os: linux
     dist: trusty
     sudo: required
     compiler: gcc
   - os: linux
     dist: trusty
     sudo: required
     compiler: clang
   - os: osx
     osx_image: xcode7.3

addons:
  apt:
    packages:
    - libyajl-dev
    - libyaml-dev

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yajl libyaml; fi
